export const CLIENTES_MTZ = [
  {
    id: '0217',
    nombre: 'NORTH CENTER GPS SPA',
    rut: '77094091-5',
    email: 'contacto@northcentergps.cl',
    telefono: '+56 57 2123456',
    direccion: 'Av. Arturo Prat 1234',
    comuna: 'Iquique',
    region: 'Tarapacá',
    facturacion: 15105727,
    crecimiento: 12.5,
    estado: 'Premium',
    fechaRegistro: '2019-03-15',
    ultimaFactura: '2025-07-12',
    contactoPrincipal: {
      nombre: 'Juan Pérez González',
      cargo: 'Gerente General',
      telefono: '+56 9 8765 4321',
      email: 'jperez@northcentergps.cl',
    },
    avatar: 'NC',
    color: 'bg-blue-500',
  },
  {
    id: '0400',
    nombre: 'INVERSIONES Y DESARROLLO MINERO SPA',
    rut: '77345678-9',
    email: 'contacto@inversionesmineras.cl',
    telefono: '+56 55 567 8901',
    direccion: 'Av. Grecia 2500',
    comuna: 'Antofagasta',
    region: 'Antofagasta',
    facturacion: 8750000,
    crecimiento: 8.2,
    estado: 'Premium',
    fechaRegistro: '2024-01-15',
    ultimaFactura: '2025-07-08',
    contactoPrincipal: {
      nombre: 'María González',
      cargo: 'Gerente Financiero',
      telefono: '+56 9 7654 3210',
      email: 'mgonzalez@inversionesmineras.cl',
    },
    avatar: 'IM',
    color: 'bg-orange-500',
  },
  {
    id: '0300',
    nombre: 'CONSTRUCTORA MARTINEZ Y ASOCIADOS SPA',
    rut: '76123456-7',
    email: 'contacto@martinezconstructora.cl',
    telefono: '+56 2 2345 6789',
    direccion: 'Av. Las Condes 1234, Oficina 506',
    comuna: 'Las Condes',
    region: 'Metropolitana',
    facturacion: 4500000,
    crecimiento: 18.7,
    estado: 'Activo',
    fechaRegistro: '2025-07-10',
    ultimaFactura: '2025-07-15',
    contactoPrincipal: {
      nombre: 'Ing. Roberto Martinez',
      cargo: 'Gerente General',
      telefono: '+56 9 5432 1098',
      email: 'rmartinez@martinezconstructora.cl',
    },
    avatar: 'CM',
    color: 'bg-green-500',
  },
  {
    id: '0402',
    nombre: 'AGRICOLA VALLE VERDE SPA',
    rut: '79567890-1',
    email: 'ventas@valleverde.cl',
    telefono: '+56 34 678 9012',
    direccion: 'Ruta 5 Sur Km 180',
    comuna: 'Rancagua',
    region: 'O\'Higgins',
    facturacion: 5200000,
    crecimiento: 5.8,
    estado: 'Estacional',
    fechaRegistro: '2023-09-10',
    ultimaFactura: '2025-06-30',
    contactoPrincipal: {
      nombre: 'Carlos Herrera',
      cargo: 'Jefe de Ventas',
      telefono: '+56 9 4321 0987',
      email: 'cherrera@valleverde.cl',
    },
    avatar: 'AV',
    color: 'bg-emerald-500',
  },
  {
    id: '0401',
    nombre: 'TECNOLOGIA AVANZADA CHILE LTDA',
    rut: '76890123-4',
    email: 'info@tecnologiaavanzada.cl',
    telefono: '+56 2 3456 7890',
    direccion: 'Av. Providencia 1234, Oficina 801',
    comuna: 'Providencia',
    region: 'Metropolitana',
    facturacion: 3200000,
    crecimiento: 25.3,
    estado: 'VIP',
    fechaRegistro: '2025-01-20',
    ultimaFactura: '2025-07-14',
    contactoPrincipal: {
      nombre: 'Dra. Ana Silva',
      cargo: 'CEO',
      telefono: '+56 9 3210 9876',
      email: 'asilva@tecnologiaavanzada.cl',
    },
    avatar: 'TA',
    color: 'bg-purple-500',
  },
];

export const ESTADOS_CLIENTE = [
  'Activo',
  'Inactivo',
  'Premium',
  'VIP',
  'Estacional',
];

export const REGIONES_CHILE = [
  'Arica y Parinacota',
  'Tarapacá',
  'Antofagasta',
  'Atacama',
  'Coquimbo',
  'Valparaíso',
  'Metropolitana',
  'O\'Higgins',
  'Maule',
  'Ñuble',
  'Biobío',
  'La Araucanía',
  'Los Ríos',
  'Los Lagos',
  'Aysén',
  'Magallanes',
];

export const TIPOS_EMPRESA = [
  'Persona Natural',
  'SPA',
  'LTDA',
  'SA',
  'EIRL',
  'Sociedad Colectiva',
  'Sociedad en Comandita',
];